### PR TITLE
added steps to set up Twitter API in the readme

### PR DESCRIPTION
**Pull request by Parthiv-M**
I have added the steps to set up the Twitter API. Please have a look.

### CODE REVIEW

**Review by TaniaMalhotra — CHANGES_REQUESTED** [review]
This looks good to me
Can you please shift this section after the "How to run the bot in your terminal" section?

**Comment by Parthiv-M** [comment]
> This looks good to me
> Can you please shift this section after the "How to run the bot in your terminal" section?

I have done the required changes!

**Comment by TaniaMalhotra** [comment]
Thank you for your contribution @Parthiv-M 🎉

**Comment by TaniaMalhotra** [comment]
Do leave a star to support my work!

**Pull request merged**
